# Generated by Django 3.1.2 on 2020-10-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Книги')),
                ('author', models.ManyToManyField(to='handbook.Author', verbose_name='Автор/Авторы книги')),
                ('genre', models.ManyToManyField(to='handbook.BookGenre', verbose_name='Жанр/Жанры книги')),
                ('publishing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbook.publishinghouse', verbose_name='Издательство')),
                ('seria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handbook.bookseria', verbose_name='Серия книги')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('books', models.ManyToManyField(to='book.Book', verbose_name='Книги')),
            ],
        ),
    ]
