# Generated by Django 3.1.2 on 2020-10-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='Название Книги')),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.bookauthor')),
            ],
        ),
    ]
